-- The demo project's canonical schema, living in the Postgres schema `main`.
--
-- Shaped so the interesting migrations are natural rather than contrived:
--   * orders.amount is integer cents  -> retyping to numeric(14,2) forces a full
--     table rewrite, which is the expand/backfill/contract demo.
--   * customers.email is varchar(255) -> widening to text is metadata-only, which
--     is the contrast case: same-looking operation, completely different cost.
--   * orders.notes is nullable        -> SET NOT NULL exercises the CHECK NOT VALID path.

-- Dropped and recreated rather than created IF NOT EXISTS. A seed script has to produce a KNOWN
-- state: with IF NOT EXISTS, a column someone renamed in an earlier session survives the "reset"
-- and every later step is working against a schema it does not expect.
DROP SCHEMA IF EXISTS main CASCADE;
CREATE SCHEMA main;

CREATE TABLE main.customers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       varchar(255) NOT NULL,
    full_name   text         NOT NULL,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE main.products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         varchar(64)  NOT NULL,
    name        text         NOT NULL,
    price_cents integer      NOT NULL,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT products_sku_key UNIQUE (sku),
    CONSTRAINT products_price_nonneg CHECK (price_cents >= 0)
);

-- The large table. Everything about the migration story happens here.
CREATE TABLE main.orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint       NOT NULL REFERENCES main.customers(id),
    status      varchar(32)  NOT NULL DEFAULT 'pending',
    amount      integer      NOT NULL,
    notes       text,
    placed_at   timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX orders_customer_idx  ON main.orders (customer_id);
CREATE INDEX orders_placed_at_idx ON main.orders (placed_at);

CREATE TABLE main.order_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint  NOT NULL REFERENCES main.orders(id) ON DELETE CASCADE,
    product_id      bigint  NOT NULL REFERENCES main.products(id),
    quantity        integer NOT NULL DEFAULT 1,
    unit_price_cents integer NOT NULL,
    CONSTRAINT order_items_qty_positive CHECK (quantity > 0)
);

CREATE INDEX order_items_order_idx ON main.order_items (order_id);
