package com.schemasync.catalog;

import com.schemasync.PostgresTestBase;
import com.schemasync.core.model.*;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class SchemaIntrospectorTest extends PostgresTestBase {

    private SchemaIntrospector introspector() {
        return new SchemaIntrospector(jdbc);
    }

    private String demoSchema(String label) {
        String s = freshSchema(label);
        jdbc.execute("""
                CREATE TABLE %s.customers (
                    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email      varchar(255) NOT NULL,
                    full_name  text         NOT NULL,
                    created_at timestamptz  NOT NULL DEFAULT now(),
                    CONSTRAINT customers_email_key UNIQUE (email)
                )""".formatted(s));
        jdbc.execute("""
                CREATE TABLE %s.orders (
                    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id bigint      NOT NULL REFERENCES %s.customers(id) ON DELETE CASCADE,
                    status      varchar(32) NOT NULL DEFAULT 'pending',
                    amount      integer     NOT NULL,
                    notes       text,
                    placed_at   timestamptz NOT NULL DEFAULT now()
                )""".formatted(s, s));
        jdbc.execute("CREATE INDEX orders_customer_idx ON %s.orders (customer_id)".formatted(s));
        jdbc.execute("CREATE INDEX orders_recent_idx ON %s.orders (placed_at DESC) WHERE notes IS NOT NULL".formatted(s));
        return s;
    }

    @Test
    @DisplayName("reads tables, columns, types and nullability out of the real catalog")
    void readsColumns() {
        SchemaSnapshot snap = introspector().introspect(demoSchema("cols"));

        assertThat(snap.tables()).hasSize(2);
        TableDef orders = snap.tableByName("orders");
        assertThat(orders).isNotNull();

        ColumnDef amount = orders.columnByName("amount");
        assertThat(amount.type().sql()).isEqualTo("integer");
        assertThat(amount.nullable()).isFalse();

        ColumnDef notes = orders.columnByName("notes");
        assertThat(notes.type().sql()).isEqualTo("text");
        assertThat(notes.nullable()).isTrue();

        // The canonicaliser earning its keep: Postgres reports this as
        // "character varying(32)", not as the varchar(32) that was written.
        assertThat(orders.columnByName("status").type().sql()).isEqualTo("varchar(32)");
    }

    @Test
    @DisplayName("Postgres' rewritten default is canonicalised back to what the user wrote")
    void canonicalisesDefaults() {
        SchemaSnapshot snap = introspector().introspect(demoSchema("defaults"));
        TableDef orders = snap.tableByName("orders");

        // Stored by Postgres as 'pending'::character varying.
        assertThat(orders.columnByName("status").defaultExpr()).isEqualTo("'pending'");
        assertThat(orders.columnByName("placed_at").defaultExpr()).isEqualTo("now()");

        // An identity column's nextval() default is dropped: the sequence name is derived from
        // the table and column, so it would change under a rename while the semantics do not.
        ColumnDef id = orders.columnByName("id");
        assertThat(id.defaultExpr()).isNull();
        assertThat(id.identity()).isEqualTo("BY DEFAULT");
    }

    @Test
    @DisplayName("constraints and indexes reference columns by stable id, not by name")
    void readsConstraintsAndIndexes() {
        SchemaSnapshot snap = introspector().introspect(demoSchema("cons"));
        TableDef orders = snap.tableByName("orders");
        TableDef customers = snap.tableByName("customers");

        ConstraintDef fk = orders.constraints().values().stream()
                .filter(c -> c.kind() == ConstraintDef.Kind.FOREIGN_KEY)
                .findFirst().orElseThrow();
        assertThat(fk.references().tableId()).isEqualTo(customers.id());
        assertThat(fk.references().onDelete()).isEqualTo("CASCADE");
        // The FK's local column id must actually resolve to customer_id in this table.
        assertThat(orders.columns().get(fk.columnIds().get(0)).name()).isEqualTo("customer_id");

        assertThat(orders.constraints().values())
                .anyMatch(c -> c.kind() == ConstraintDef.Kind.PRIMARY_KEY);
        assertThat(customers.constraints().values())
                .anyMatch(c -> c.kind() == ConstraintDef.Kind.UNIQUE);

        IndexDef partial = orders.indexes().values().stream()
                .filter(i -> i.name().equals("orders_recent_idx"))
                .findFirst().orElseThrow();
        assertThat(partial.predicate()).isNotNull();
        assertThat(partial.columns().get(0).direction()).isEqualTo("DESC");
    }

    @Test
    @DisplayName("re-introspecting an unchanged schema yields an identical hash")
    void reIntrospectionIsHashStable() {
        // This is the test that proves canonicalisation works. Without it, every re-import
        // produces a phantom diff and both drift detection and no-op detection are worthless.
        String schema = demoSchema("stable");
        SchemaSnapshot first = introspector().introspect(schema);
        SchemaSnapshot second = introspector().introspect(schema, first);

        assertThat(SnapshotHasher.hash(second)).isEqualTo(SnapshotHasher.hash(first));
    }

    @Test
    @DisplayName("stable ids are carried forward, so identity does not churn on re-import")
    void carriesStableIdsForward() {
        String schema = demoSchema("ids");
        SchemaSnapshot first = introspector().introspect(schema);
        SchemaSnapshot second = introspector().introspect(schema, first);

        String firstAmountId = first.tableByName("orders").columnByName("amount").id();
        String secondAmountId = second.tableByName("orders").columnByName("amount").id();
        assertThat(secondAmountId).isEqualTo(firstAmountId);
    }

    @Test
    @DisplayName("a real rename keeps the column's id, so it can never diff as drop + add")
    void renameKeepsIdentity() {
        String schema = demoSchema("rename");
        SchemaSnapshot before = introspector().introspect(schema);
        String amountId = before.tableByName("orders").columnByName("amount").id();

        // Simulate the rename having been applied, re-introspecting with the ORIGINAL name map.
        // Introspection alone cannot know a rename happened -- that is exactly why the operation
        // API carries the intent. Here we assert the surrounding mechanics: the id is minted per
        // (table, name), so a rename that goes through the API keeps its id explicitly.
        jdbc.execute("ALTER TABLE %s.orders RENAME COLUMN amount TO total_amount".formatted(schema));
        SchemaSnapshot after = introspector().introspect(schema, before);

        String renamedId = after.tableByName("orders").columnByName("total_amount").id();
        // Introspecting a rename we were not told about mints a NEW id -- which is precisely the
        // drift the DRIFTED state exists to catch, and why free-form SQL is not accepted.
        assertThat(renamedId).isNotEqualTo(amountId);
        assertThat(SnapshotHasher.hash(after)).isNotEqualTo(SnapshotHasher.hash(before));
    }

    @Test
    @DisplayName("unsupported objects are recorded, never silently dropped")
    void recordsUnmanagedObjects() {
        String schema = demoSchema("unmanaged");
        jdbc.execute("CREATE VIEW %s.recent_orders AS SELECT * FROM %s.orders".formatted(schema, schema));

        SchemaSnapshot snap = introspector().introspect(schema);

        // Omitting these would be worse than not supporting them: the merge plan is
        // diff(target, merged), so a missing object looks exactly like a deleted one and the
        // merge would drop the view from the real database.
        assertThat(snap.isPartiallyManaged()).isTrue();
        assertThat(snap.unmanaged())
                .anyMatch(u -> u.kind().equals("view") && u.name().equals("recent_orders"));
    }
}
